services:
  app:
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - AUTH_URL=${AUTH_URL}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: nextjs-app
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./package-lock.json
        - action: rebuild
          path: ./next.config.js
        - action: sync
          path: .
          target: /app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - gestionganadera:/data/db
volumes:
  gestionganadera:
