FROM mongo:latest

COPY backup.sh /backup.sh
RUN chmod +x /backup.sh

# Ejecutar el script todos los días a las 2 AM
RUN echo "0 2 * * * /backup.sh >> /var/log/backup.log 2>&1" > /etc/cron.d/mongo-backup
RUN chmod 0644 /etc/cron.d/mongo-backup && \
    crontab /etc/cron.d/mongo-backup

CMD ["cron", "-f"]
